### ISSUE TITLE
[rccextended] Compile

### ISSUE THREAD

**Issue by MVoz** [zedxxx/rccextended#2]
как собрать эту утилитку, можно пару строк в ридми добавить?
чтобы не методом тыка изучать

**Comment by zedxxx** [comment]
Всё довольно просто: надо установить Qt и QtCreator (под Windows QtCreator ставится совместно с Qt, одним инсталлером), открыть в QtCreator файл проекта [rcc.po](https://github.com/zedxxx/rccextended/blob/master/src/rcc.pro) и выполнить билд.

**Comment by MVoz** [comment]
@zedxxx компиляторы все есть, и даже больше
компилятор какой используется msvc или mingw?
из командной строки как?

**Comment by zedxxx** [comment]
Я использовал MSYS2 с MinGW-w64 и статической версией Qt (`mingw-w64-i686-qt5-static`). 

Соответственно, из командной строки MSYS2, проект собирается при помощи `qmake` (генерирует Makefile) и `make`: 
```
qmake rcc.pro
make
```

**Comment by zedxxx** [comment]
И да, на вкладке releases есть уже скомпилированная версия: https://github.com/zedxxx/rccextended/releases

**Comment by MVoz** [comment]
@zedxxx  спасибо, раскидаюсь с делами, попробую, отпишусь и закрою

**Comment by playing4living** [comment]
А я под линукс собрать всё пытаюсь, а уже под винду скомпиленное есть, так даже лучше. Огромное спасибо за утилиту.
