### ISSUE TITLE
Unknown module(s) in QT: core xml

### ISSUE THREAD

**Issue by almaceleste** [zedxxx/rccextended#3]
пытаюсь скомпилировать под линукс.
`qmake rcc.pro` говорит:
```
Info: creating stash file /tmp/rcc/rccextended-3/src/.qmake.stash
Project ERROR: Unknown module(s) in QT: core xml
```
не понимаю, что он от меня хочет.

**Comment by zedxxx** [comment]
Нужно установить пакеты `qt5-default` и `qtdeclarative5-dev`:
        
        sudo apt install qt5-default qtdeclarative5-dev

**Comment by almaceleste** [comment]
пакет `qt5-default` пока не доступен в версии Ubuntu 21.04.  
но оказалось, что достаточно установить `qtdeclarative5-dev`.
