### ISSUE TITLE
After compiling back, the file becomes smaller, opening the software and reporting an error

### ISSUE THREAD

**Issue by gududexiaocao** [zedxxx/rccextended#4]
I don't know how to write code. I'm not a programmer. Although he is open source, when I use him, I find that the compiled file is smaller than the source file, and after replacing it, it opens and reports an error. I will attach the project.Hope you see it can be fixed
<img width="714" alt="Snipaste_2022-07-28_00-22-48" src="https://user-images.githubusercontent.com/26451407/181299071-af6c4a1c-284e-490b-a0d2-a3a6b8c5135e.png">
Project Files：https://drive.google.com/file/d/1Xzd7m55IPdZpurhVuEkf383GyWiqeMI2/view?usp=sharing

**Comment by BeckyDTP** [comment]
It's not true.
Compiled file rcc (by `make.bat` from rcc\qresource\rcc folder) is the same as compiled (675840 bytes).
"Bigger" file in the source in folder (823296 bytes) is older [18 July 2022] and you can delete it.

**Comment by gududexiaocao** [comment]
> It's not true. Compiled file rcc (by `make.bat` from rcc\qresource\rcc folder) is the same as compiled (675840 bytes). "Bigger" file in the source in folder (823296 bytes) is older [18 July 2022] and you can delete it.

Yes, I know that the 803kb file is the source file, and the 659kb file is the compiled file. You can see that it has become smaller, and I will replace it and open the software and report an error

**Comment by zedxxx** [comment]
1. Try change `--format-version` from 1 to 2 in the make.bat
2. Try add option `--no-compress` in the make.bat

**Comment by gududexiaocao** [comment]
> 

Thank you, I tried it and it still doesn't work. Is there any other solution?
![image](https://user-images.githubusercontent.com/26451407/181397578-4042bc05-29e2-42c5-ac3b-efd2e4eba135.png)

**Comment by zedxxx** [comment]
There are 2 files with the same name but whit different letters case in your .rcc file:

  `:/plugin/ICMaterialUI/UVSetting.ui`
  `:/plugin/ICMaterialUI/Uvsetting.ui`

So, extracting this .rcc under Windows will cause a bug with missing `Uvsetting.ui` in resulting folder and in the repacked resource file. 

If you will try repack your .rcc under Linux (Ubuntu) everything should work fine. I don't know how to fix it under Windows yet.

**Comment by gududexiaocao** [comment]
> .rcc 文件中有 2 个名称相同但字母大小写不同的文件：
> 
> `:/plugin/ICMaterialUI/UVSetting.ui` `:/plugin/ICMaterialUI/Uvsetting.ui`
> 
> 因此，在 Windows 下提取此 .rcc 将导致`Uvsetting.ui`结果文件夹和重新打包的资源文件中丢失的错误。
> 
> 如果您尝试在 Linux (Ubuntu) 下重新打包您的 .rcc，一切都应该可以正常工作。我还不知道如何在 Windows 下修复它。

Please how can I extract or package under Linux you don't seem to provide a Linux version

**Comment by zedxxx** [comment]
Yes, you must compile it by yourself from sources. See #2 and #3 for some howto.

**Comment by gududexiaocao** [comment]
> 是的，您必须自己从源代码编译它。有关一些操作方法，请参见#2。
sorry i really don't understand，can you help compile a copy

**Comment by gududexiaocao** [comment]
> 是的，您必须自己从源代码编译它。有关一些操作方法，请参见#2和#3。

![image](https://user-images.githubusercontent.com/26451407/181753047-470c44fd-ca75-4fb2-970c-cfd630679ca9.png)
I tried my best and gave up

**Comment by zedxxx** [comment]
How to compile under Linux:

1. Install Ubuntu
2. Install Qt5 packages: `sudo apt install qt5-default qtdeclarative5-dev`
3. Clone this repository: `git clone https://github.com/zedxxx/rccextended`
4. Navigate to the `src` folder: `cd rccextended/src/` 
5. Compile it: `qmake rcc.pro && make`
6. Move compiled binary to .local/bin: `mv -v rcc ~/.local/bin/`

Now you can decompile your .rcc file as usual. But, to compile it back you can't use make.bat now. You need to write a 
`rcc-make.sh` script (save it in the same folder as make.bat and don't forget to make it executable). Script content is:
```
#!/usr/bin/bash
opt="--verbose --format-version 3 --binary"
rcc $opt ./../qrc/ICMaterialUI.qrc -o ./../rcc/ICMaterialUI.rcc
```

**Comment by zedxxx** [comment]
@gududexiaocao Test this release candidate build: [rcc-v1.0.5-rc1.zip](https://github.com/zedxxx/rccextended/files/9381393/rcc-v1.0.5-rc1.zip)

- fixed file names collision issue;
- fixed extraction of localized resources (previous version extracts resources only for the default locale)

I have done a lot of refactoring and don't test it a lot yet, so something can goes wrong. Test it carefully.

**Comment by gududexiaocao** [comment]
> @gududexiaocao Test this release candidate build: [rcc-v1.0.5-rc1.zip](https://github.com/zedxxx/rccextended/files/9381393/rcc-v1.0.5-rc1.zip)
> 
> * fixed file names collision issue;
> * fixed extraction of localized resources (previous version extracts resources only for the default locale)
> 
> I have done a lot of refactoring and don't test it a lot yet, so something can goes wrong. Test it carefully.

Great, tested and solved it perfectly, thank you very much for your efforts
